apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: forgejo
      version: "12.x"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system
  values:
    service:
      http:
        type: LoadBalancer
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: true
    redis-cluster:
      enabled: false
    redis:
      enabled: false
    gitea:
      config:
        cache:
          ADAPTER: memory
        session:
          PROVIDER: memory
        queue:
          TYPE: level
